/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateTodoArgs } from "./CreateTodoArgs";
import { UpdateTodoArgs } from "./UpdateTodoArgs";
import { DeleteTodoArgs } from "./DeleteTodoArgs";
import { TodoCountArgs } from "./TodoCountArgs";
import { TodoFindManyArgs } from "./TodoFindManyArgs";
import { TodoFindUniqueArgs } from "./TodoFindUniqueArgs";
import { Todo } from "./Todo";
import { TodoService } from "../todo.service";
@graphql.Resolver(() => Todo)
export class TodoResolverBase {
  constructor(protected readonly service: TodoService) {}

  async _todosMeta(
    @graphql.Args() args: TodoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Todo])
  async todos(@graphql.Args() args: TodoFindManyArgs): Promise<Todo[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => Todo, { nullable: true })
  async todo(@graphql.Args() args: TodoFindUniqueArgs): Promise<Todo | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Todo)
  async createTodo(@graphql.Args() args: CreateTodoArgs): Promise<Todo> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Todo)
  async updateTodo(@graphql.Args() args: UpdateTodoArgs): Promise<Todo | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Todo)
  async deleteTodo(@graphql.Args() args: DeleteTodoArgs): Promise<Todo | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
